### ISSUE TITLE
Allow Tor users on *.asbru-cm.net

### ISSUE THREAD

**Issue by lukejohnsonrp** [asbru-cm/asbru-cm.github.io#1]
Currently the Cloudflare account serving asbru-cm.net and *.asbru-cm.net is configured to block Tor users and require them to pass captcha or javascript human verification. Their captcha is often broken and sometimes don't let Tor users to pass it.

It would be great if you could whitelist Tor users in the Cloudflare account serving these sites, so there will never be issues with accessibility of your site. Here is a short guide on how to do it https://github.com/allow-tor/on-cloudflare

Right now my browser stuck on this page and it doesn't load the captcha or anything else:

![Screenshot_2020-10-23_11-41-37](https://user-images.githubusercontent.com/60250230/96999498-c26f1d80-1524-11eb-94ad-9e6cd18ffa46.png)

Whitelisting Tor users in Cloudflare would resolve this issue.

**Comment by KlaasT** [comment]
I added a firewall rule to allow Tor users to our site. Should be ready in about a minute. If there is any other issue feel free to reopen.

**Comment by lukejohnsonrp** [comment]
It seems the problem still persists, could you please recheck.

**Comment by lukejohnsonrp** [comment]
Resolved, thank you.
